const express=require('express');
const cookieParser=require('cookie-parser');
const multer=require('multer');
const crypto=require('crypto');
const fs=require('fs');
const zlib=require('zlib');
const path=require('path');
const {spawnSync}=require('child_process');
require('dotenv').config();
const db=require('./db');
const supabase=require('./lib/supabase');
const {CAPS}=require('./lib/scoring');
const app=express();
// Ensure Express 4 forwards rejected async handlers to the shared error boundary.
for(const method of ['get','post','put','patch','delete']){const register=app[method].bind(app);app[method]=(...args)=>{if(args.length===1)return register(...args);const [route,...handlers]=args;return register(route,...handlers.map(h=>h?.constructor?.name==='AsyncFunction'?(req,res,next)=>Promise.resolve(h(req,res,next)).catch(next):h))}}

const PORT=Number(process.env.PORT||3000);
const uploadDir=path.resolve(process.env.UPLOAD_DIR||path.join(__dirname,'data','uploads'));fs.mkdirSync(uploadDir,{recursive:true});
app.disable('x-powered-by');
app.use(require('./lib/security').headers);
app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'public')));
const upload=multer({dest:uploadDir,limits:{fileSize:12*1024*1024},fileFilter:(_r,f,cb)=>cb(null,['application/pdf','text/plain','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/zip'].includes(f.mimetype)||/\.(pdf|txt|doc|docx|zip)$/i.test(f.originalname))});
function passwordHash(password,salt=crypto.randomBytes(16).toString('hex')){return {salt,hash:crypto.scryptSync(password,salt,64).toString('hex')}}
function verifyPassword(p,s,e){const a=crypto.scryptSync(p,s,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(a,'hex'),Buffer.from(e,'hex'))}
function auth(req,res,next){const t=req.cookies.hireme_session,u=t&&db.getSession(t);if(!u)return res.status(401).json({error:'Authentication required'});req.user=u;next()}
function role(r){return (req,res,next)=>{if(req.user.role!==r)return res.status(403).json({error:`${r} access required`});next()}}
function sha256(file){const h=crypto.createHash('sha256');return new Promise((resolve,reject)=>{const s=fs.createReadStream(file);s.on('data',d=>h.update(d));s.on('end',()=>resolve(h.digest('hex')));s.on('error',reject)})}
function ascii85Decode(input){const s=input.replace(/\s/g,'').replace(/^<~/,'').replace(/~>$/,'');const bytes=[];let value=0,count=0;for(const c of s){if(c==='z'&&count===0){bytes.push(0,0,0,0);continue}const n=c.charCodeAt(0)-33;if(n<0||n>84)continue;value=value*85+n;if(++count===5){bytes.push(value>>>24,(value>>>16)&255,(value>>>8)&255,value&255);value=0;count=0}}if(count){for(let i=count;i<5;i++)value=value*85+84;for(let i=0;i<count-1;i++)bytes.push((value>>>(24-i*8))&255)}return Buffer.from(bytes)}
function extractPdfFallback(file){try{const pdf=fs.readFileSync(file,'latin1'),texts=[];for(const match of pdf.matchAll(/\/Filter\s*\[\s*\/ASCII85Decode\s*\/FlateDecode[\s\S]*?stream\r?\n([\s\S]*?)\r?\n?endstream/g)){texts.push(zlib.inflateSync(ascii85Decode(match[1])).toString('latin1'))}return texts.join('\n')}catch{return ''}}
function extractPdf(file){try{const r=spawnSync('python',['-c',`import fitz,sys; d=fitz.open(sys.argv[1]); print('\\n'.join(p.get_text() for p in d))`,file],{encoding:'utf8',timeout:15000});if(r.status===0&&r.stdout)return r.stdout}catch{}return extractPdfFallback(file)}
function detectSkills(text){const lower=` ${(text||'').toLowerCase()} `;const found=db.skills().filter(s=>lower.includes(s.name.toLowerCase())).map(s=>s.name);const aliases={'machine learning':'Machine Learning','deep learning':'Machine Learning','data analysis':'SQL','data analytics':'SQL','computer vision':'Computer Vision','mlops':'MLOps','pytorch':'PyTorch','opencv':'OpenCV','postgres':'PostgreSQL','postgresql':'PostgreSQL','time series':'Time Series','javascript':'JavaScript','react':'React','docker':'Docker','python':'Python','sql':'SQL','aws':'AWS','git':'Git','yolo':'YOLO'};for(const [term,skill] of Object.entries(aliases))if(lower.includes(term.toLowerCase()))found.push(skill);return [...new Set(found)]}
require('./routes/core')(app,{db,auth,role,upload,uploadDir,passwordHash,verifyPassword,sha256,extractPdf,detectSkills});
app.get('/api/health',(_q,r)=>r.json({ok:true,name:'HireMe.co',version:'2.0.0',supabase_configured:supabase.configured(),supabase_storage_configured:supabase.storageConfigured()}));
app.post('/api/auth/register',require('./lib/security').authLimit,(req,res)=>{const {name,email,password,role:requestedRole='employee'}=req.body||{};const role=requestedRole==='employer'?'employer':'employee';if(!name||!email||!password||typeof password!=='string'||password.length<8||password.length>128||typeof name!=='string'||typeof email!=='string')return res.status(400).json({error:'Name, email and 8–128 character password are required'});const e=email.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)||name.length>120)return res.status(400).json({error:'Enter a valid email and name'});if(db.getUserByEmail(e))return res.status(409).json({error:'Account already exists'});const p=passwordHash(password),u=db.createUser(name.trim(),e,p.hash,p.salt,role),t=crypto.randomBytes(32).toString('hex');db.session(t,u.id);res.cookie('hireme_session',t,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*864e5});res.json({user:db.getProfile(u.id)})});
app.post('/api/auth/login',require('./lib/security').authLimit,(req,res)=>{const u=db.getUserByEmail((req.body.email||'').trim().toLowerCase());if(!u||!verifyPassword(req.body.password||'',u.salt,u.password_hash))return res.status(401).json({error:'Invalid email or password'});const t=crypto.randomBytes(32).toString('hex');db.session(t,u.id);res.cookie('hireme_session',t,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*864e5});res.json({user:db.getProfile(u.id)})});
app.post('/api/auth/logout',(req,res)=>{if(req.cookies.hireme_session)db.deleteSession(req.cookies.hireme_session);res.clearCookie('hireme_session');res.json({ok:true})});app.get('/api/me',auth,(req,res)=>res.json({user:db.getProfile(req.user.id)}));
app.put('/api/profile',auth,(req,res)=>{const allowed=['phone','education','college','course','target_role','interests','freelance_rate','availability','portfolio'];const p={};for(const k of allowed)if(req.body[k]!==undefined)p[k]=String(req.body[k]);if(req.body.name)db.update('users',req.user.id,{name:String(req.body.name)});db.updateProfile(req.user.id,p);res.json({user:db.getProfile(req.user.id)})});
app.get('/api/dashboard',auth,(req,res)=>res.json(db.dashboard(req.user.id)));app.get('/api/skills',auth,(req,res)=>res.json(db.userSkills(req.user.id)));app.get('/api/roadmap',auth,(req,res)=>res.json(db.roadmap(req.user.id)));app.get('/api/opportunities',auth,(req,res)=>res.json(db.filter('opportunities',o=>o.status==='active').map(o=>db.matchOpportunity(req.user.id,o))));app.get('/api/internships',auth,(req,res)=>res.json(db.filter('opportunities',o=>o.status==='active'&&o.type==='internship').map(o=>db.matchOpportunity(req.user.id,o)).sort((a,b)=>b.match_score-a.match_score)));app.get('/api/notifications',auth,(req,res)=>res.json(db.filter('notifications',n=>n.user_id===req.user.id).sort((a,b)=>b.created_at.localeCompare(a.created_at))));
app.post('/api/notifications/:id/read',auth,(req,res)=>{const n=db.find('notifications',n=>n.id===Number(req.params.id)&&n.user_id===req.user.id);if(!n)return res.status(404).json({error:'Notification not found'});db.update('notifications',n.id,{read:true});res.json({ok:true})});
app.get('/api/evidence',auth,(req,res)=>res.json(db.filter('evidence',e=>e.user_id===req.user.id).sort((a,b)=>b.created_at.localeCompare(a.created_at))));
app.post('/api/evidence',auth,upload.single('evidence'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Upload a supported evidence file'});const hash=await sha256(req.file.path);const browserText=String(req.body.extracted_text||'').slice(0,100000);let text=browserText;if(!text&&/\.txt$/i.test(req.file.originalname))text=fs.readFileSync(req.file.path,'utf8').slice(0,100000);else if(!text&&(/\.pdf$/i.test(req.file.originalname)||req.file.mimetype==='application/pdf'))text=extractPdf(req.file.path).slice(0,100000);const names=detectSkills(text+' '+req.file.originalname);const skillName=req.body.skill||names[0];if(skillName&&!db.skillByName(skillName))db.upsertUserSkill(req.user.id,String(skillName).slice(0,80));const skill=skillName&&db.skillByName(skillName);const duplicate=db.find('evidence',e=>e.user_id===req.user.id&&e.sha256===hash);if(duplicate){fs.unlinkSync(req.file.path);return res.status(409).json({error:'Duplicate evidence detected; it cannot earn points twice',evidence:duplicate})}if(skill)db.upsertUserSkill(req.user.id,skill.name,{source:'Uploaded evidence'});const type=req.body.type||'self_declared';const points=type==='self_declared'?CAPS.self_declared:CAPS[type]||0;const auto=type!=='self_declared';const e=db.addEvidence({user_id:req.user.id,name:req.file.originalname,mime:req.file.mimetype,path:req.file.path,sha256:hash,text,skill_id:skill?.id||null,type,points,verified:auto,status:auto?'auto_verified':'self_declared',verification_method:auto?'document_analysis':'self_declaration'});if(skill){db.upsertUserSkill(req.user.id,skill.name,{source:'Uploaded evidence'});db.recalcSkill(req.user.id,skill.id)}for(const n of names){db.upsertUserSkill(req.user.id,n,{source:'Evidence extraction'});const s=db.skillByName(n);if(s&&s.id!==skill?.id)db.recalcSkill(req.user.id,s.id)}res.json({evidence:e,detected_skills:names,hash,parser:browserText?'browser PDF extraction':text?'server text extraction':'no readable text',auto_verified:auto})});
app.get('/api/tests',auth,(_req,res)=>res.json(db.data.assessments));
app.post('/api/tests',auth,role('employer'),(req,res)=>res.status(201).json(db.add('assessments',{title:req.body.title,skill:req.body.skill,difficulty:req.body.difficulty||'Intermediate',questions:req.body.questions||[]})));
app.post('/api/assessments/seed',auth,(req,res)=>{const existing=db.data.assessments;if(!existing.length){db.add('assessments',{title:'Python Foundations',skill:'Python',difficulty:'Beginner',questions:[{q:'Which type is immutable?',options:['list','dict','tuple','set'],a:2},{q:'What does len([1,2,3]) return?',options:['2','3','4','Error'],a:1},{q:'Which keyword defines a function?',options:['func','def','function','lambda'],a:1}]});db.add('assessments',{title:'MLOps Essentials',skill:'Docker',difficulty:'Intermediate',questions:[{q:'A Docker image is...',options:['running container','template for containers','database','network'],a:1},{q:'Which file defines Docker build steps?',options:['Dockerfile','docker.json','compose.txt','Container.js'],a:0},{q:'Docker Compose is mainly for...',options:['multi-container apps','GPU drivers','SQL queries','DNS'],a:0}]});}res.json(db.data.assessments)});
app.get('/api/tests/:id',auth,(req,res)=>{const t=db.find('assessments',x=>x.id===Number(req.params.id));if(!t)return res.status(404).json({error:'Test not found'});res.json(t)});
app.post('/api/tests/:id/attempt',auth,async(req,res)=>{const t=db.find('assessments',x=>x.id===Number(req.params.id));if(!t)return res.status(404).json({error:'Test not found'});let correct=0;(t.questions||[]).forEach((q,i)=>{if(Number.isInteger(req.body.answers?.[i])&&req.body.answers[i]===Number(q.a))correct++});const score=Math.round(correct/(t.questions.length||1)*100);const points=db.assessmentPoints(score);db.add('attempts',{user_id:req.user.id,assessment_id:t.id,score,passed:score>=70,answers:req.body.answers||[]});const s=db.skillByName(t.skill);if(s){db.upsertUserSkill(req.user.id,s.name,{source:'Assessment'});const e=db.addEvidence({user_id:req.user.id,name:`${t.title} assessment`,mime:'application/json',path:'',sha256:crypto.createHash('sha256').update(`${req.user.id}:${t.id}:${score}`).digest('hex'),text:'',skill_id:s.id,type:'assessment',points,verified:true});db.recalcSkill(req.user.id,s.id);res.json({score,points,passed:score>=70,correct,total:t.questions.length,evidence:e});return}res.json({score,points,passed:score>=70,correct,total:t.questions.length})});
app.post('/api/applications',auth,role('employee'),(req,res)=>{const opportunity_id=Number(req.body.opportunity_id);const o=db.find('opportunities',x=>x.id===opportunity_id);if(!o)return res.status(404).json({error:'Opportunity not found'});if(o.status!=='active'||(o.deadline&&new Date(o.deadline+'T23:59:59Z')<new Date()))return res.status(400).json({error:'This opportunity is closed'});const existing=db.find('applications',a=>a.user_id===req.user.id&&a.opportunity_id===opportunity_id);if(existing)return res.status(409).json({error:'Already applied'});const m=db.matchOpportunity(req.user.id,o);if(!m.eligible)return res.status(400).json({error:'You do not meet the hard requirements for this opportunity'});db.add('match_scores',{user_id:req.user.id,opportunity_id,criteria:m.breakdown,weights:m.breakdown.map(b=>({skill:b.skill,weight:b.weight})),final_score:m.match_score,eligible:m.eligible,explanation:m.explanation,engine_version:m.engine_version});const a=db.add('applications',{user_id:req.user.id,opportunity_id,status:'submitted',match_score:m.match_score,score_snapshot:{...m,company:undefined},cover_letter:String(req.body.cover_letter||'').slice(0,5000)});db.add('notifications',{user_id:req.user.id,title:'Application submitted',body:`Your application for ${o.title} was submitted.`});res.status(201).json(a)});
app.get('/api/roles',auth,(req,res)=>res.json(db.data.career_roles.map(r=>({...r,requirements:db.filter('role_requirements',x=>x.role_id===r.id)}))));
app.get('/api/challenges',auth,(req,res)=>res.json(db.data.challenges.map(c=>({...c,company:db.find('companies',x=>x.id===c.company_id),skills:db.filter('project_skills',x=>x.project_id===c.id)}))));
app.post('/api/challenges/:id/submit',auth,upload.single('file'),(req,res)=>{const c=db.find('challenges',x=>x.id===Number(req.params.id));if(!c)return res.status(404).json({error:'Challenge not found'});res.json(db.add('challenge_submissions',{challenge_id:c.id,user_id:req.user.id,title:req.body.title||'Submission',description:req.body.description||'',file:req.file?.filename||null,status:'submitted'}))});
app.get('/api/projects',auth,(req,res)=>res.json(db.filter('projects',p=>p.owner_id===req.user.id||db.find('project_members',m=>m.project_id===p.id&&m.user_id===req.user.id)).map(p=>({...p,skills:db.filter('project_skills',x=>x.project_id===p.id),members:db.filter('project_members',x=>x.project_id===p.id)}))));
app.post('/api/projects',auth,(req,res)=>{const p=db.add('projects',{owner_id:req.user.id,title:req.body.title,description:req.body.description,deadline:req.body.deadline||'',github:req.body.github||'',progress:0});(req.body.skills||[]).forEach(s=>db.add('project_skills',{project_id:p.id,skill:s}));db.add('project_members',{project_id:p.id,user_id:req.user.id,role:'Owner'});res.status(201).json(p)});
app.get('/api/courses',auth,(req,res)=>res.json(db.data.courses.map(c=>({...c,skills:db.filter('course_skills',x=>x.course_id===c.id)}))));
app.get('/api/feed',auth,(req,res)=>res.json(db.data.feed_posts.map(p=>({...p,comments:db.filter('comments',c=>c.post_id===p.id)})).sort((a,b)=>b.created_at.localeCompare(a.created_at))));
app.post('/api/feed',auth,(req,res)=>res.status(201).json(db.savePost(req.user.id,req.body.content,req.body.kind||'post')));
app.post('/api/feed/:id/comment',auth,(req,res)=>res.status(201).json(db.add('comments',{post_id:Number(req.params.id),user_id:req.user.id,author_name:db.getProfile(req.user.id).name,content:req.body.content})));
app.post('/api/feed/:id/like',auth,(req,res)=>{const p=db.find('feed_posts',x=>x.id===Number(req.params.id));if(!p)return res.status(404).json({error:'Post not found'});const existing=db.find('likes',x=>x.user_id===req.user.id&&x.target_type==='post'&&x.target_id===p.id);if(existing){db.remove('likes',existing.id);db.update('feed_posts',p.id,{likes:Math.max(0,(p.likes||0)-1)});}else{db.add('likes',{user_id:req.user.id,target_type:'post',target_id:p.id});db.update('feed_posts',p.id,{likes:(p.likes||0)+1});}res.json({likes:db.find('feed_posts',x=>x.id===p.id).likes})});
app.get('/api/messages',auth,(req,res)=>res.json(db.filter('messages',m=>m.from_user_id===req.user.id||m.to_user_id===req.user.id).sort((a,b)=>a.created_at.localeCompare(b.created_at))));
app.post('/api/messages',auth,(req,res)=>{const m=db.add('messages',{from_user_id:req.user.id,to_user_id:Number(req.body.to_user_id),content:req.body.content});db.add('notifications',{user_id:Number(req.body.to_user_id),title:'New message',body:`${db.getProfile(req.user.id).name} sent you a message.`,read:false});res.status(201).json(m)});
app.get('/api/employer/company',auth,role('employer'),(req,res)=>res.json(db.find('companies',c=>c.owner_id===req.user.id)||null));
app.put('/api/employer/company',auth,role('employer'),(req,res)=>{let c=db.find('companies',x=>x.owner_id===req.user.id);if(!c)c=db.add('companies',{owner_id:req.user.id});res.json(db.update('companies',c.id,{name:req.body.name,industry:req.body.industry,location:req.body.location,description:req.body.description}))});
app.post('/api/employer/opportunities',auth,role('employer'),require('./lib/security').validateOpportunity,(req,res)=>{let c=db.find('companies',x=>x.owner_id===req.user.id);if(!c)c=db.add('companies',{owner_id:req.user.id,name:'Company'});const o=db.add('opportunities',{company_id:c.id,title:req.body.title,type:req.body.type||'job',description:req.body.description||'',location:req.body.location||'Remote',compensation:req.body.compensation||'',deadline:req.body.deadline||'',status:'active'});(req.body.skills||[]).forEach(s=>db.add('opportunity_skills',{opportunity_id:o.id,skill:s.name||s.skill,weight:Number(s.weight||0),importance:s.importance||'preferred',minimum_score:Number(s.minimum_score||0)}));res.status(201).json(db.matchOpportunity(req.user.id,o))});
app.get('/api/employer/opportunities',auth,role('employer'),(req,res)=>{const c=db.find('companies',x=>x.owner_id===req.user.id);res.json(db.filter('opportunities',o=>o.company_id===c?.id&&o.status!=='deleted').map(o=>({...o,skills:db.filter('opportunity_skills',s=>s.opportunity_id===o.id)})))});
app.get('/api/employer/candidates',auth,role('employer'),(req,res)=>{const oppId=Number(req.query.opportunity_id);const opp=db.find('opportunities',o=>o.id===oppId);if(!opp||!db.find('companies',c=>c.id===opp.company_id&&c.owner_id===req.user.id))return res.status(404).json({error:'Opportunity not found'});const candidates=db.data.users.filter(u=>u.role==='employee').map(u=>{const x=db.matchOpportunity(u.id,opp);return {...x,candidate:db.publicProfile(u.id),skills:db.userSkills(u.id)}}).sort((a,b)=>b.match_score-a.match_score);res.json(candidates)});
app.get('/api/employer/analytics',auth,role('employer'),(req,res)=>{const c=db.find('companies',x=>x.owner_id===req.user.id);const opps=db.filter('opportunities',o=>o.company_id===c?.id&&o.status!=='deleted');const apps=db.filter('applications',a=>opps.some(o=>o.id===a.opportunity_id));const allSkills={};db.data.employee_skills.forEach(s=>{const n=db.skillById(s.skill_id)?.name;if(n)allSkills[n]=(allSkills[n]||0)+1});res.json({active_jobs:opps.filter(o=>o.type==='job'&&o.status==='active').length,active_internships:opps.filter(o=>o.type==='internship'&&o.status==='active').length,applications:apps.length,top_skills:Object.entries(allSkills).sort((a,b)=>b[1]-a[1]).slice(0,8),candidate_readiness:db.data.users.filter(u=>u.role==='employee').map(u=>db.readiness(u.id)),skill_demand:opps.flatMap(o=>db.filter('opportunity_skills',s=>s.opportunity_id===o.id)).reduce((m,s)=>(m[s.skill]=(m[s.skill]||0)+1,m),{})})});
app.get('/api/employer/documents',auth,role('employer'),(req,res)=>res.json(db.filter('employer_documents',x=>x.user_id===req.user.id)));
app.post('/api/employer/documents',auth,role('employer'),upload.single('document'),async(req,res)=>{if(!req.file)return res.status(400).json({error:'Upload a document'});const hash=await sha256(req.file.path);let text=req.file.mimetype==='application/pdf'?extractPdf(req.file.path):/\.txt$/i.test(req.file.originalname)?fs.readFileSync(req.file.path,'utf8'):'';const skills=detectSkills(text+' '+req.file.originalname);const suggestions=skills.map((s,i)=>({skill:s,importance:i<2?'High':'Medium',reason:'Detected repeatedly in employer-provided evidence'}));const d=db.add('employer_documents',{user_id:req.user.id,name:req.file.originalname,path:req.file.path,sha256:hash,text,ai_suggestions:suggestions,status:'pending_review'});res.json({document:d,suggestions})});
app.get('/api/employer/preferences',auth,role('employer'),(req,res)=>res.json(db.employerPreference(req.user.id)));
app.post('/api/employer/preferences/confirm',auth,role('employer'),require('./lib/security').validateCriteria,(req,res)=>{const skills=(req.body.skills||[]).filter(s=>String(s.skill||'').trim());const total=skills.reduce((sum,s)=>sum+Number(s.weight||0),0);if(!skills.length)return res.status(400).json({error:'Add at least one skill preference'});if(total!==100)return res.status(400).json({error:`Skill weights must total 100%. Current total: ${total}%`});const p=db.add('employer_preferences',{user_id:req.user.id,status:'confirmed',source_document_id:req.body.source_document_id||null,confirmed_at:new Date().toISOString()});skills.forEach(s=>db.add('employer_skill_weights',{preference_id:p.id,skill:String(s.skill).trim(),weight:Number(s.weight||0),importance:['required','preferred','optional'].includes(s.importance)?s.importance:'preferred',minimum_score:Math.max(0,Math.min(100,Number(s.minimum_score||0)))}));res.json(db.employerPreference(req.user.id))});
app.get('/api/employer/candidate-feed',auth,role('employer'),(req,res)=>res.json(db.candidateFeed(req.user.id)));
app.get('/api/industry-insights',auth,(req,res)=>{const demand={};db.data.opportunity_skills.forEach(x=>demand[x.skill]=(demand[x.skill]||0)+Number(x.weight||1));const avail={};db.data.employee_skills.forEach(x=>{const n=db.skillById(x.skill_id)?.name;if(n)avail[n]=(avail[n]||0)+1});res.json({demand,availability:avail,comparison:Object.keys({...demand,...avail}).map(k=>({skill:k,demand:demand[k]||0,availability:avail[k]||0,gap:(demand[k]||0)-(avail[k]||0)})).sort((a,b)=>b.gap-a.gap)})});
app.get('/api/reputation',auth,(req,res)=>res.json(db.find('reputation',x=>x.user_id===req.user.id)||{user_id:req.user.id,score:0}));
app.get('/api/social-links',auth,(req,res)=>res.json(db.filter('social_links',x=>x.user_id===req.user.id)));
app.post('/api/social-links',auth,(req,res)=>res.status(201).json(db.add('social_links',{user_id:req.user.id,provider:req.body.provider,url:req.body.url,verified:false}))); 
app.get('/api/talent',auth,role('employer'),(req,res)=>{const q=String(req.query.q||'').toLowerCase(),skill=String(req.query.skill||'').toLowerCase(),min=Math.max(0,Math.min(100,Number(req.query.min_score||0)));const out=db.data.users.filter(u=>u.role==='employee').map(u=>({candidate:db.publicProfile(u.id),skills:db.userSkills(u.id),readiness:db.readiness(u.id)})).filter(x=>!q||x.candidate.name.toLowerCase().includes(q)||String(x.candidate.target_role||'').toLowerCase().includes(q)).filter(x=>!skill||x.skills.some(s=>s.skill.name.toLowerCase().includes(skill)&&s.score>=min));res.json(out)});
// Employers own their criteria: updating a role replaces its criteria with the submitted set.
app.put('/api/employer/opportunities/:id',auth,role('employer'),require('./lib/security').validateOpportunity,(req,res)=>{const o=db.find('opportunities',x=>x.id===Number(req.params.id));const c=db.find('companies',x=>x.owner_id===req.user.id);if(!o||o.company_id!==c?.id)return res.status(404).json({error:'Opportunity not found'});const fields=['title','type','description','location','compensation','deadline','status'];const patch={};fields.forEach(k=>{if(req.body[k]!==undefined)patch[k]=String(req.body[k])});db.update('opportunities',o.id,patch);if(Array.isArray(req.body.skills)){db.filter('opportunity_skills',s=>s.opportunity_id===o.id).forEach(s=>db.remove('opportunity_skills',s.id));req.body.skills.filter(s=>s.skill).forEach(s=>db.add('opportunity_skills',{opportunity_id:o.id,skill:String(s.skill).trim(),weight:Number(s.weight||0),importance:['required','preferred','optional'].includes(s.importance)?s.importance:'preferred',minimum_score:Number(s.minimum_score||0)}));}res.json({...db.find('opportunities',x=>x.id===o.id),skills:db.filter('opportunity_skills',s=>s.opportunity_id===o.id)});});
app.get('/api/employer/skills',auth,role('employer'),(_req,res)=>res.json(db.skills().map(s=>s.name)));
app.get('/api/evidence-records',auth,(req,res)=>res.json(db.evidenceSummary(req.user.id)));
app.post('/api/evidence-records',auth,(req,res)=>{const r=db.createRecord(req.user.id,req.body||{});res.status(201).json(db.recordForUser(req.user.id,r.id))});
app.get('/api/evidence-records/:id',auth,(req,res)=>{const r=db.recordForUser(req.user.id,req.params.id);if(!r)return res.status(404).json({error:'Record not found'});res.json(r)});
app.patch('/api/evidence-records/:id',auth,(req,res)=>{const r=db.recordForUser(req.user.id,req.params.id);if(!r)return res.status(404).json({error:'Record not found'});const fields=['title','organization','role','start_date','end_date','description','claims','links','visibility'];const patch={};fields.forEach(k=>{if(req.body[k]!==undefined)patch[k]=String(req.body[k])});db.update('candidate_records',r.id,patch);db.auditRecord(r.id,'Record updated','Candidate updated record details');db.recalcRecord(r.id);res.json(db.recordForUser(req.user.id,r.id))});
app.delete('/api/evidence-records/:id',auth,(req,res)=>{const r=db.recordForUser(req.user.id,req.params.id);if(!r)return res.status(404).json({error:'Record not found'});db.filter('record_audit',d=>d.record_id===r.id).forEach(d=>db.remove('record_audit',d.id));db.filter('candidate_documents',d=>d.record_id===r.id).forEach(d=>db.remove('candidate_documents',d.id));db.filter('candidate_claims',d=>d.record_id===r.id).forEach(d=>db.remove('candidate_claims',d.id));db.filter('candidate_record_skills',d=>d.record_id===r.id).forEach(d=>db.remove('candidate_record_skills',d.id));db.remove('candidate_records',r.id);res.json({ok:true})});
app.post('/api/evidence-records/:id/documents',auth,upload.single('document'),async(req,res)=>{const r=db.recordForUser(req.user.id,req.params.id);if(!r)return res.status(404).json({error:'Record not found'});if(!req.file)return res.status(400).json({error:'Upload a document'});const hash=await sha256(req.file.path);if(db.find('candidate_documents',d=>d.user_id===req.user.id&&d.sha256===hash))return res.status(409).json({error:'Possible duplicate document: it is already linked to an evidence record'});let text=req.body.extracted_text||'';if(!text&&/\.txt$/i.test(req.file.originalname))text=fs.readFileSync(req.file.path,'utf8');else if(!text&&/\.pdf$/i.test(req.file.originalname))text=extractPdf(req.file.path);const skills=detectSkills(text+' '+r.title+' '+r.description);const doc=db.add('candidate_documents',{record_id:r.id,user_id:req.user.id,name:req.file.originalname,path:req.file.path,mime:req.file.mimetype,sha256:hash,text:String(text).slice(0,100000),status:'ANALYZED',visibility:r.visibility});skills.forEach(skill=>{if(!db.find('candidate_record_skills',s=>s.record_id===r.id&&s.skill===skill))db.add('candidate_record_skills',{record_id:r.id,skill,source_document_id:doc.id})});const claimText=r.claims||`${r.title}${r.role?` — ${r.role}`:''}`;if(claimText)db.add('candidate_claims',{record_id:r.id,claim:claimText,status:'DOCUMENT SUPPORTED',document_id:doc.id,page:1});db.auditRecord(r.id,'Document analyzed',`${doc.name}: ${skills.length} related skills identified`);db.recalcRecord(r.id);res.status(201).json({document:doc,record:db.recordForUser(req.user.id,r.id),detected_skills:skills})});
app.use(require('./lib/security').errors);
app.use('/api',(_q,r)=>r.status(404).json({error:'API route not found'}));app.get('*',(_q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));if(require.main===module)db.ready.then(()=>app.listen(PORT,'127.0.0.1',()=>console.log(`HireMe.co running at http://localhost:${PORT}`)));
module.exports=app;
