require('dotenv').config();process.env.SEED_DEMO='true';const db=require('../db'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
if(process.env.NODE_ENV==='production')throw Error('Demo seed is disabled in production');
db.seed();
const password=process.env.DEMO_PASSWORD||crypto.randomBytes(12).toString('base64url');
function user(name,email,role){let u=db.getUserByEmail(email);if(u)return u;const salt=crypto.randomBytes(16).toString('hex');return db.createUser(name,email,crypto.scryptSync(password,salt,64).toString('hex'),salt,role)}
const recruiter=user('Priya Sharma','recruiter@hireme.co','employer');const company=db.find('companies',c=>c.owner_id===recruiter.id);db.update('companies',company.id,{name:'Nexa AI',industry:'AI & Software',location:'Bengaluru',description:'We build practical AI products and help early-career engineers grow.'});
const cands=[user('Alex Morgan','demo@hireme.co','employee'),user('Maya Patel','maya@hireme.co','employee'),user('Rohan Das','rohan@hireme.co','employee')];
for(const [index,u]of cands.entries()){
 db.updateProfile(u.id,{education:'B.Tech Computer Science',college:['National Institute of Technology','College of Engineering Pune','Government Engineering College'][index],course:'Computer Science',target_role:index===1?'Data Analyst':'Machine Learning Engineer',interests:'Applied AI, open source, thoughtful products',availability:'Available for internships'});
 for(const name of ['Python','Machine Learning','SQL','Git','PyTorch','React','JavaScript']){const s=db.upsertUserSkill(u.id,name);for(const [type,points]of Object.entries({self_declared:5,academic:10,certification:10,assessment:index===2?8:17,project:20,...(index===0?{mentor:10,industry:15}:{})})){const hash=`demo:${u.id}:${s.skill_id}:${type}`;if(!db.find('evidence',e=>e.sha256===hash))db.addEvidence({user_id:u.id,skill_id:s.skill_id,name:`Demo ${name} ${type} record`,sha256:hash,type,points,verified:type!=='self_declared',status:type==='self_declared'?'self_declared':'approved',demo:true})}db.recalcSkill(u.id,s.skill_id)}
 if(!db.find('projects',p=>p.owner_id===u.id)){const p=db.add('projects',{owner_id:u.id,title:['Resume Insight Engine','Campus Energy Dashboard','Open Source Issue Explorer'][index],description:'An end-to-end college project with documented implementation, evaluation, and lessons learned.',progress:85,github:''});db.add('project_members',{project_id:p.id,user_id:u.id,role:'Owner'});for(const skill of ['Python','SQL'])db.add('project_skills',{project_id:p.id,skill})}
 if(!db.find('candidate_records',r=>r.user_id===u.id)){db.createRecord(u.id,{type:'education',title:'B.Tech Computer Science',organization:db.getProfile(u.id).college,description:'Algorithms, database systems, and software engineering',visibility:'EMPLOYERS'});db.createRecord(u.id,{type:'internship',title:'Software Engineering Intern',organization:'Campus Innovation Lab',role:'Engineering Intern',description:'Built data tools for a faculty research group.',visibility:'EMPLOYERS'})}
}
for(const o of db.data.opportunities)if(!db.find('companies',c=>c.id===o.company_id)?.owner_id)db.update('opportunities',o.id,{company_id:company.id,deadline:new Date(Date.now()+90*864e5).toISOString().slice(0,10)});
if(!db.find('opportunities',o=>o.title==='Frontend Developer Intern')){const o=db.add('opportunities',{company_id:company.id,title:'Frontend Developer Intern',type:'internship',description:'Create accessible React interfaces and ship useful features with a small product team.',location:'Remote',compensation:'₹22,000 / month',status:'active',deadline:new Date(Date.now()+90*864e5).toISOString().slice(0,10)});for(const [skill,weight]of [['React',40],['JavaScript',35],['Git',25]])db.add('opportunity_skills',{opportunity_id:o.id,skill,weight,importance:'preferred',minimum_score:30})}
for(const [i,u]of cands.entries()){const o=db.data.opportunities[i],m=db.matchOpportunity(u.id,o);if(!db.find('applications',a=>a.user_id===u.id&&a.opportunity_id===o.id)){db.add('applications',{user_id:u.id,opportunity_id:o.id,status:i===0?'shortlisted':'submitted',match_score:m.match_score,score_snapshot:m,cover_letter:'I would love to contribute my project experience and keep learning with your team.'});db.add('match_scores',{user_id:u.id,opportunity_id:o.id,criteria:m.breakdown,weights:m.breakdown.map(b=>({skill:b.skill,weight:b.weight})),final_score:m.match_score,explanation:m.explanation,engine_version:m.engine_version})}}
const folder=path.dirname(require('../lib/storage').filename),credentialFile=path.join(folder,'demo-credentials.txt');if(!fs.existsSync(credentialFile))fs.writeFileSync(credentialFile,`Local demonstration accounts (never deploy these accounts):\nCandidate: demo@hireme.co\nRecruiter: recruiter@hireme.co\nPassword: ${password}\n`);console.log(`Demo ready. Account details: ${credentialFile}`);
